In [1]:
import  numpy as np

## DataTypes AND Attributes


In [5]:
## numpy main datatype is ndarray i.e n dimensional array
a1=np.array([1,2,3,4])
a1
type(a1)

numpy.ndarray

In [6]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
##shape
a1.shape


(4,)

In [10]:
a2.shape


(2, 3)

In [11]:

a3.shape

(1, 6, 3)

In [12]:
##size
a1.size

4

In [13]:
a2.size

6

In [14]:
a3.size

18

In [15]:
a1.dtype

dtype('int64')

In [16]:
a2.dtype

dtype('int64')

In [17]:
a3.dtype

dtype('int64')

In [18]:
a1.ndim

1

In [19]:
a2.ndim

2

In [20]:
a3.ndim

3

In [22]:
# creating a dataframe using a numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## CREATING ARRAYS

In [27]:
## CREATE AN ARRAY FILLED WITH ONES
ones=np.ones((2,3),dtype="int")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
## CREATE AN ARRAY FILLED WITH ZEROES
zeroes=np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
## CREATE AN ARRAY WITH A PARTICULAR RANGE
rangarray=np.arange(0,10,2)
rangarray

array([0, 2, 4, 6, 8])

In [36]:
##Creating a random array
randm=np.random.randint(1,10,(3,5))
randm

array([[9, 5, 3, 8, 1],
       [7, 6, 5, 9, 3],
       [5, 2, 8, 1, 7]], dtype=int32)

In [34]:
np.random.random(size=(2,2)) ## bw 0 and 1

array([[0.57838101, 0.8348507 ],
       [0.85378302, 0.77155727]])

In [35]:
np.random.rand(1,3)

array([[0.86482094, 0.83173081, 0.84116133]])

In [38]:
## Random seed
np.random.seed(0)
np.random.randint(0,10,(2,2))

array([[5, 0],
       [3, 3]], dtype=int32)

## VIEWING ARRAY AND MATRICES

In [43]:
np.random.seed(0)
randomarr=np.random.randint(0,10,(2,3))
randomarr

                            

array([[5, 0, 3],
       [3, 7, 9]], dtype=int32)

In [45]:
np.unique(randomarr,sorted="False")

array([0, 3, 5, 7, 9], dtype=int32)

In [51]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [52]:
a3[1][2][0]

np.int64(16)

In [61]:
a3[1][:2]

array([[10, 11, 12],
       [13, 14, 15]])

In [64]:
a4=np.random.randint(0,10,(2,3,4,5))
a4

array([[[[3, 0, 0, 6, 0],
         [6, 3, 3, 8, 8],
         [8, 2, 3, 2, 0],
         [8, 8, 3, 8, 2]],

        [[8, 4, 3, 0, 4],
         [3, 6, 9, 8, 0],
         [8, 5, 9, 0, 9],
         [6, 5, 3, 1, 8]],

        [[0, 4, 9, 6, 5],
         [7, 8, 8, 9, 2],
         [8, 6, 6, 9, 1],
         [6, 8, 8, 3, 2]]],


       [[[3, 6, 3, 6, 5],
         [7, 0, 8, 4, 6],
         [5, 8, 2, 3, 9],
         [7, 5, 3, 4, 5]],

        [[3, 3, 7, 9, 9],
         [9, 7, 3, 2, 3],
         [9, 7, 7, 5, 1],
         [2, 2, 8, 1, 5]],

        [[8, 4, 0, 2, 5],
         [5, 0, 8, 1, 1],
         [0, 3, 8, 8, 4],
         [4, 0, 9, 3, 7]]]], dtype=int32)

In [67]:
a4[0][:4]

array([[[3, 0, 0, 6, 0],
        [6, 3, 3, 8, 8],
        [8, 2, 3, 2, 0],
        [8, 8, 3, 8, 2]],

       [[8, 4, 3, 0, 4],
        [3, 6, 9, 8, 0],
        [8, 5, 9, 0, 9],
        [6, 5, 3, 1, 8]],

       [[0, 4, 9, 6, 5],
        [7, 8, 8, 9, 2],
        [8, 6, 6, 9, 1],
        [6, 8, 8, 3, 2]]], dtype=int32)

## Manipulating arrays
## ARITHMETIC


In [70]:
oness=np.ones((2,2))
newarray=np.array([[1,2],[3,4]])
oness+newarray


array([[2., 3.],
       [4., 5.]])

In [71]:
newarray-oness

array([[0., 1.],
       [2., 3.]])

In [72]:
newarray * oness

array([[1., 2.],
       [3., 4.]])

In [73]:
##multiplication

In [74]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [81]:
## Reshaping
a6=a2.reshape(2,3,1)
a6*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

## Aggregation
Aggregation - bringing things together, doing a similar thing on a number of things.

In [82]:
a1

array([1, 2, 3, 4])

In [83]:
np.sum(a1)

np.int64(10)

In [84]:
sum(a1)

np.int64(10)

## pythons sum vs numpy sum
use pythons when using python data typpes use numpy wala when using numpy ndarray

In [86]:
massivearray=np.random.random(100000)

In [88]:
massivearray[:10]

array([0.67909062, 0.86428144, 0.75084425, 0.96448977, 0.55424244,
       0.2123905 , 0.22244322, 0.21874937, 0.56957353, 0.45210904])

In [89]:
%timeit sum(massivearray)

7.55 ms ± 940 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [91]:
%timeit np.sum(massivearray)

40.7 μs ± 1.78 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
listy=list([1,2,3,4,5,6,7])
listy



In [98]:
%timeit np.sum(listy)

7.56 μs ± 1.28 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [99]:
%timeit sum(listy)

101 ns ± 2.76 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


## VARIENCE AND STANDARD DEVIATION


In [100]:
AR1=np.array([1,100,300,500,900])
AR2=np.array([2,4,6,8,10])
np.var(AR1)
np.var(AR2)

np.float64(8.0)

In [101]:
np.var(AR1)

np.float64(102256.16)

## DOT PRODUCT EXAMPLE

In [104]:
np.random.seed(0)
array1=np.random.randint(0,10,(5,3))
import pandas as pd
pd.DataFrame(array1,index=["Mon","Tues","Wed","Thurs","Fri"], columns=["Almond Butter","Peanut Butter","Cashew Butter"])

Almond Butter  Peanut Butter  Cashew Butter
Mon                5              0              3
Tues               3              7              9
Wed                3              5              2
Thurs              4              7              6
Fri                8              8              1

## SORTING

In [106]:
sortingarray=np.random.randint(0,10,(2,3))
sortingarray

array([[6, 7, 7],
       [8, 1, 5]], dtype=int32)

In [107]:
np.sort(sortingarray)

array([[6, 7, 7],
       [1, 5, 8]], dtype=int32)

In [108]:
sortingarray

array([[6, 7, 7],
       [8, 1, 5]], dtype=int32)

In [109]:
np.argsort(sortingarray)

array([[0, 1, 2],
       [1, 2, 0]])

In [110]:
np.argmin(sortingarray)

np.int64(4)

In [112]:
np.argmax(sortingarray)

np.int64(3)

In [113]:
np.argmax(sortingarray,axis=0)

array([1, 0, 0])

In [114]:
np.argmax(sortingarray,axis=1)

array([1, 0])

## ARRAY OF IMAGES


In [116]:
from matplotlib.image import imread
panda=imread("panda.png")
type(panda)

numpy.ndarray

In [117]:
panda[:5]


array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [120]:
dog=imread("dog-photo.png")
dog.size,dog.ndim,dog.shape,dog.dtype

(993600, 3, (432, 575, 4), dtype('float32'))